[phases.setup]
nixPkgs = ["nodejs_18", "npm"]

[phases.install]
cmds = [
  "rm -rf node_modules/.cache",
  "npm install --omit=dev --prefer-offline --no-audit"
]

[phases.build]
cmds = ["echo 'Build phase completed'"]

[start]
cmd = "npm start"
